name: flutter_project
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  lottie: ^3.1.2
  gap: ^3.0.1
  toastification: ^2.1.0
  dio: ^5.5.0+1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  flutter_dotenv: ^5.1.0
  google_places_flutter: ^2.0.9
  skeletonizer: ^1.4.1+1
  quickalert: ^1.1.0
  image_cropper: ^8.0.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  http_parser: ^4.0.2
  mime: ^1.0.5
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.4.0
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  sms_autofill: ^2.4.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  easy_sidemenu: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/ic_image_placeholder.png
    - assets/icon/Vector.png
    - assets/icon/Edit.png
    - assets/icon/eye-closed.png
    - assets/icon/Hide.png
    - assets/icon/Hide.svg
    - assets/icon/ic_no_wifi.png
    - assets/lottie/empty_lottie.json
    - assets/lottie/error_lottie.json
    - assets/lottie/no_notification_lottie.json
    - assets/lottie/page_not_found.json
    - assets/lottie/welcome_lottie.json
    - assets/secrets/dotenv.env
    - assets/icon/
    - assets/svg_icons/
    - assets/images/

