/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'flutter_project';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String IC_IMAGE_PLACEHOLDER =
      'assets/icon/ic_image_placeholder.png';
  static const String IC_NO_WIFI = 'assets/icon/ic_no_wifi.png';
  static const String EMPTY_LOTTIE = 'assets/lottie/empty_lottie.json';
  static const String ERROR_LOTTIE = 'assets/lottie/error_lottie.json';
  static const String NO_NOTIFICATION_LOTTIE =
      'assets/lottie/no_notification_lottie.json';
  static const String MENU_ICON = 'assets/icon/menu.png';
  static const String ARROW = 'assets/icon/arrow.png';
  static const String DASHBOARD = 'assets/icon/dashboard.png';
  static const String PROFILE = 'assets/icon/profile.png';
  static const String PAGE_NOT_FOUND = 'assets/lottie/page_not_found.json';
  static const String WELCOME_LOTTIE = 'assets/lottie/welcome_lottie.json';
  static const String DOTENV = 'assets/secrets/dotenv.env';
}
