/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'flutter_project';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String IC_IMAGE_PLACEHOLDER =
      'assets/icon/ic_image_placeholder.png';
  static const String IC_NO_WIFI = 'assets/icon/ic_no_wifi.png';
  static const String EMPTY_LOTTIE = 'assets/lottie/empty_lottie.json';
  static const String ERROR_LOTTIE = 'assets/lottie/error_lottie.json';
  static const String NO_NOTIFICATION_LOTTIE =
      'assets/lottie/no_notification_lottie.json';
  static const String PAGE_NOT_FOUND = 'assets/lottie/page_not_found.json';
  static const String WELCOME_LOTTIE = 'assets/lottie/welcome_lottie.json';
  static const String DOTENV = 'assets/secrets/dotenv.env';
  static const String HIDE_PASSWORD = 'assets/icon/Hide.svg';
  static const String EYE_CLOSED = 'assets/icon/eye-closed.svg';
  //images
  static const String PASSWORD1 = 'assets/images/1 967.png';
  static const String PASSWORD2 = 'assets/images/2 1.png';
  static const String PASSWORD3 = 'assets/images/3 59417.png';

  //provoder
  static const String check = 'assets/icon/Vector.png';
  static const String edit = 'assets/icon/Edit.png';
}
