// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQJo5l9_xU5H5p4cum7EfgD9FtBn9-owM',
    appId: '1:494109479290:web:6b6448a82976aedc9286c3',
    messagingSenderId: '494109479290',
    projectId: 'project5242',
    authDomain: 'project5242.firebaseapp.com',
    storageBucket: 'project5242.appspot.com',
    measurementId: 'G-6SB1S0P1H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFrgKSXTjtGV2GwuE3K-epOq8GrL844JU',
    appId: '1:494109479290:android:6e4cbba3db186f149286c3',
    messagingSenderId: '494109479290',
    projectId: 'project5242',
    storageBucket: 'project5242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ0pX3jqvO2i2fyasT-4WJpqLxIlJinAM',
    appId: '1:494109479290:ios:3388d068bd7049d39286c3',
    messagingSenderId: '494109479290',
    projectId: 'project5242',
    storageBucket: 'project5242.appspot.com',
    iosBundleId: 'com.app.flutterProject',
  );
}
